### ISSUE TITLE
Copie intelligente

### ISSUE THREAD

**Issue by CiotOfficial** [CiotHub/Ciot-Projects#1]
Demande envoyé à Arman pour copie intelligente.

**Comment by CiotOfficial** [comment]
Appel avec Arman effectué, il va envoiller quote à Charles sous peu.

**Comment by CharlesMoreau** [comment]
Pas encore recu la quote (message test)

**Comment by jbvibert** [comment]
Rapelle fait a Arman

**Comment by jbvibert** [comment]
On a recu la quote. En attente du dev.

**Comment by jbvibert** [comment]
Arman as mal au dos. N'a pas livré encore....

**Comment by jbvibert** [comment]
Installer et tester.
