### ISSUE TITLE
Signature HTML

### ISSUE THREAD

**Issue by jbvibert** [CiotHub/Ciot-Projects#14]
1. Faire template Excel pour création du template HMTL de signature

2. Faire documentation sur comment reswitcher un email en HTML

**Comment by jbvibert** [comment]
1. Template Fait
1. Outil de génération automatique de la hiéarchie contenant le fichier .htm + dossier d'image de chaque employé.
1. En test par charles

**Comment by jbvibert** [comment]
Refait en 1 table HTML

En train de commencer a regarder comment faire le script de déploiement powershell ou vb

**Comment by jbvibert** [comment]
Script fait. Mais necessite d'activé le service de registre à distance localement.

Donc Carlo et Gino vont passé de poste en et utilisé 2 script que j'ai fais. le premier va copier la signature a la bonne place et la setter comme default pour newmessage et reply.

Le deuxieme va demarrer le service RegistreaDistance et le meetre à automatique.

La prochaine fois nous pourrons donc déployer sans probleme partout à partir d'un poste admin et de mon master script Powershell.

**Comment by jbvibert** [comment]
Il faut retiré "Inc" des signature aillant Technica Inc.

**Comment by CiotOfficial** [comment]
En cour. Plus besoin de ticket.
