### ISSUE TITLE
Ceramic Data Cleanup

### ISSUE THREAD

**Issue by jbvibert** [CiotHub/Ciot-Projects#19]
Pour éviter les situations du genre "Paul export une série de produit, travaille dessus pendant 25 jour, mais Liane à fait des changement le 10e jour. Entrainant ainsi des ereurs lors du load"

Nous allons appliquer le processus suivant :
1. Lors de l'exportation, créer une copie de l'exportation orginal (dans une autre feuille) et BIEN LA NOMMÉE POUR NE PAS SE TROMPER
2. Faire les modifs.
3. Avant l'exportation, nous sortiront les donnée du système et allons comparer avec l'original copié à l'étape 1. Cela va permettre d'identifier les changements.
4. Adapté les donnée faites en 2. avec les changements identifié.

**Comment by CiotOfficial** [comment]
Aucune nouvelle depuis aout. Doit rouler comme il faut.
