### ISSUE TITLE
Installer PW et source de donnée sur serveur crystal

### ISSUE THREAD

**Issue by CiotOfficial** [CiotHub/Ciot-Projects#2]

**Comment by jbvibert** [comment]
Rapport roule dans Crsyal report 2011 sur le Server. Mais ne fonctionne par dans le Crystal management console. Je soupsonne qui faut j'installe driver 64 bit.

**Comment by jbvibert** [comment]
J'ai installer la source de donnée, il faut maintenant changer la source dans le rapport voir si l'erreur va encore apparaitr.

**Comment by CiotOfficial** [comment]
NE sert plus vraiment à rien maintenant que l'on switch ERP.
