### ISSUE TITLE
Stone data cleanup - Sous-statut pareil pour ex. GSL et GFB

### ISSUE THREAD

**Issue by jbvibert** [CiotHub/Ciot-Projects#21]
1. Regarder avec Arman et Serge si le sous-statut M est necessaire (normalement non car cette informations peut être identifier avec la class du produit (25MFP ou quelque chose du genre). Le but étant que les 2 produit ex. GSL et GFB aillent toujours le même sous-statut afin d'éviter des confusions  et aider à la création d'étiquettes.

2. Vérifier aussi avec Arman et serge si l'onglet substitut sert à quelque chose. Si il ne sert pas, nous allons incorporer dans le processus de création d'un produit que son équivalent sera placer à cette endroit. Ceci dans le but de facilité la vie au gens consltant et cherchant les différentes équivalence. EXEMPLE  -> GSLALPIHP20

3. Vérifier si un rapport est disponible permettant de sortir les substituts.

**Comment by jbvibert** [comment]
1. Serge dit que ca lui sert a rien et croit que ca sert a personne. Reste a vérifier avec Arman,

**Comment by jbvibert** [comment]
Question envoyé à Arman

**Comment by jbvibert** [comment]
1. Arman dit aussi que c'Est juste pour le groupement/rapport pour nous. Nous sommes en processus de test et allons changer bientôt les sous statut des CTS à la même chose que leur matiere premiere.

2. L'onglet substitue ne sert a rien dans le back-end d'apres arman. C'Est seulement pour facilité la vie des gens. L'idée avancé par Ghislaine et moi est de remplacer le label du champs Quantité par quelque chose comme "type". Il va y avoir 1 type pour les vrai substitue, et un type pour le SKU CTS correspondance. Comme cela nous allons garder le fonctionnalité initial tout en l'étendant.

3. Non mais la table est inrempla. J'ai sortit un raport pour G.G

**Comment by CiotOfficial** [comment]
Supposément les gens mette l même sous-statut et le change dans les 2 produits.
