### ISSUE TITLE
Slab library

### ISSUE THREAD

**Issue by jbvibert** [CiotHub/Ciot-Projects#27]
Faire DOC + ecrire email au différent responsable.

**Comment by jbvibert** [comment]
Draft de doc faite.

**Comment by jbvibert** [comment]
Benjamin écrit le email et finalise le document. G.G approuvera et ils envveront le message bientôt.

**Comment by jbvibert** [comment]
MEssage envoyé, projet lancé.

**Comment by jbvibert** [comment]
On doit faire une dossier permettant a des fournisseur d'europe et d'ailleur de déposé des photo.

On doit créer un user exprès pour ce dossier, n'ayant pas accès au reste, que l'on donnera au supplier.

À valider avec Marco et Carlo

**Comment by CiotOfficial** [comment]
Marco n'a jamais donné de news. Ne doit pas être vraiment important.
